# Generated by Django 3.0.8 on 2020-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='uid')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.CharField(max_length=254, verbose_name='password')),
                ('country', models.CharField(max_length=254, verbose_name='country')),
                ('city', models.CharField(max_length=254, verbose_name='city')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('token', models.CharField(max_length=254, verbose_name='token')),
            ],
        ),
    ]
